# server port
server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mysql://rm-wz98eu202hx5fv84gzo.mysql.rds.aliyuncs.com:3306/recipe
    username: root
    password: qXd8b#5Y%!e2P4PcMR9zPj5XPA**
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    max-active: 150

  # redis
  redis:
    host: 120.77.180.200
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 20
        max-wait: -1
    password: ^P9eVPp737vGjpmgqo#R3#&F%s7i

  # gmail
  mail:
    host: smtp.gmail.com
    username: yyds.w09a@gmail.com
    password: yysd3600
    port: 465
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true

    properties.mail.smtp.connectiontimeout: 6000
    properties.mail.smtp.timeout: 5000
    properties.mail.smtp.writetimeout: 5000

    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    #    properties.mail.display.sendmail: COMP3900-YYDS
    default-encoding: utf-8

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

    jmx:
      domain: org.springframework.boot
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
