# server port
server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mysql://rm-wz98eu202hx5fv84gzo.mysql.rds.aliyuncs.com:3306/recipe
    username: root
    password: qXd8b#5Y%!e2P4PcMR9zPj5XPA**
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    max-active: 150

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

    jmx:
      domain: org.springframework.boot
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
